### ISSUE TITLE
Dispatcher does not recognize changes in joint order

### ISSUE THREAD

**Issue by dmronga** [rock-control/control-orogen-joint_dispatcher#2]
The dispatcher does not recognize if the order of the joint inputs changes at runtime. E.g. when I send ["joint_1", "joint_2", "joint_3"] and then later change the order to ["joint_3", "joint_2", "joint_1"] (e.g. when I disconnect the input port and connect it to a different task) the dispatcher does not realize this, but keeps passing the joint data in the wrong order. 

Is this the desired behavior? I guess that the dispatcher stores the vector indices depending on the configuration and does not check the joint order at runtime. IMO it should either throw an error if the joint order changes or perform the mapping according to the joint names passed at runtime (which would probably be abit slower than storing the indices)

**Comment by vbargsten** [comment]
Should be fixed by https://github.com/rock-control/control-joint_dispatcher/commit/be361d00e4656da1825440f6afcbae0cec1830e5
